### ISSUE TITLE
spark streaming

### ISSUE THREAD

**Issue by wenrad** [jgperrin/net.jgp.labs.spark#1]
Hello!
I want to read a csv file from spark streaming,when i run the job there is no result and the zeppelin notebook stil running for two hours ,this is my code 

```
#val spark = SparkSession
 .builder
 .appName("radhwen-streaming")
 .master("local")
 .getOrCreate()

val csvDF = spark
  .readStream
  .option("sep", ",")
  .schema(test_raw)      // Specify schema of the csv files
  .csv("/test/")
  
csvDF.writeStream
    .format("console")
    .start()
```

**Comment by jgperrin** [comment]
Hey Wenrad, there are so many reasons why this could go wrong that I cannot really make any suggestion... Maybe you should consider a post in StackOverflow? I don't know how Zeppelin handles the time out...

Are you sure files are coming?

**Comment by wenrad** [comment]
Hey,i started with useing spark.read  on the same location the job run succesfully but i want to use .readStream,im doing a test with only one file and the job is blocked for two hours until i stoped manually
